---
title: "Pilot Log"
output:
  html_document:
    df_print: paged
---

**Pilot log data**
```{r, echo=FALSE}
# data

# create pricing table
library(tibble)
library(scales)
library(knitr)

data <- tribble(
  ~date, ~aircraft.model,  ~total.duration.of.flight,
  "6/11/2010", "C-172H", 0.6,
  "7/30/2017", "C-172", 1,
  "8/19/2017", "C-172", 1.1,
  "9/9/2017", "C-172", 1,
  "9/12/2017", "C-172", 0.9,
  "9/19/2017", "C-172", 1.5,
  "10/3/2017", "C-172", 1,
  "10/6/2017", "C-172", 1.5,
  "10/21/2017","C-172", 1.6,
  "11/4/2017","C-172", 1.6,
  "11/11/2017","C-172", 1.5,
  "11/18/2017","C-172", 1.8,
  "12/02/2017","C-172", 1.3,
  "12/16/2017","C-172", 1.1
)

data$date <- as.Date(data$date, "%m/%d/%Y")

# print table
print(data)


```
**Total flight hours:**
```{r, echo=FALSE}
# print total flight hours
(total.flight.hours <- sum(data$total.duration.of.flight))
```

**Page totals:**
```{r, echo=FALSE, message = FALSE, warning = FALSE}
# add pilot log page number
rows.per.page <- 14 # enter the number of rows each page of your pilot book has

data$page.number <- NA # initialize
page.counter <- 1
for(i in seq(1,nrow(data),rows.per.page)) {
  data$page.number[i:(i+13)] <- page.counter
  page.counter <- page.counter + 1
}

# calculate page totals
library(dplyr)
data %>% 
  group_by(page.number) %>%
  summarize(page.total = sum(total.duration.of.flight))
```


